### ISSUE TITLE
Add project page

### ISSUE THREAD

**Issue by CampbellDocherty** [fac19/work-in-progress#15]
- [x] Form to submit project data
- [x] Redirect to project page
- [x] Translate DOM to React State

**Comment by jackherizsmith** [comment]
Key | Required | Description
-- | -- | --
ids[] | optional | The image ids that you want to be included in the album.
deletehashes[] | optional | The deletehashes of the images that you want to be included in the album.
title | optional | The title of the album
description | optional | The description of the album
privacy | optional | Sets the privacy level of the album. Values are : public \| hidden \| secret. Defaults to user's privacy settings for logged in users.
layout | optional | (deprecated) Sets the layout to display the album. Values are : blog \| grid \| horizontal \| vertical
cover | optional | The ID of an image that you want to be the cover of the album

**Comment by jackherizsmith** [comment]
How to upload media using JS

https://www.smashingmagazine.com/2018/01/drag-drop-file-uploader-vanilla-js/

**Comment by jackherizsmith** [comment]
How to do it in React wihtout pre-built module

https://medium.com/@650egor/simple-drag-and-drop-file-upload-in-react-2cb409d88929
